# Generated by Django 4.2 on 2023-04-11 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='TEXT',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creted_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
